name: Static-site Deployment

on:
  push:
    branches:
     - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy code to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script:  |
            sudo apt-get install -y apache2
            sudo apt-get install -y npm
            sudo apt-get install -y nodejs
            sudo apt-get update
            sudo apt-get upgrade -y
            cd /home/ubuntu/abhishek
            git pull origin main
            echo "Deployment Succesfull!!"
            npm install
            npm run build
            sudo rm -rf /home/ubuntu/var/www/html/*
            sudo mv /home/ubuntu/abhishek/build/* /var/www/html/
            systemctl apache2 restart
            echo "Deployment Succesfull!!"   